### ISSUE TITLE
Opendnd looks sick! Quick question

### ISSUE THREAD

**Issue by JakeRunsDnD** [opendnd/opendnd#2]
Hi Drew! I'm working on a discord bot over at [tavernbot](https://github.com/jakerunsdnd/tavernbot), and I stumbled across your work on a recent npm search spree. Given that we're both developing under the MIT license, it seems like I'd be clear to 'npm install --save opendnd', but I'd rather ask and make sure. 

Is it cool if I use the opendnd module for basically everything, from Nomina to Dominia? Also, will opendnd be around for a while? :)

**Comment by drewry** [comment]
Hey @jakerunsdnd, sure go right ahead! Yup we’re planning to be around for a while. I run a DnD group and use the tools myself while DMing. Keep in mind we’re not quite at a 1.0 release but we’re getting close so there may be a few bugs. Please let me know any issues you find or improvements that can be made.

**Comment by JakeRunsDnD** [comment]
Sweet! Thanks Drew! If I come across anything I'll drop an issue your way with replication steps and all that good stuff haha. Right now I'm trying to get tavernbot up to par with the dyno bot our discord group uses, and it's close, so once I hit that milestone (working toward a 1.0 myself) I'll start looking into integrating opendnd

Btw, feel free to stop by the discord, it's a DM-focused D&D group call The Order, and we're always discussing DM topics and helping each other out 😄 https://discord.gg/KBMVgq
